**1. Create a 3x3x3 array with random values**

In [5]:
import numpy as np
a = np.random.random((3,3,3))
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


**2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal**

In [6]:
import numpy as np
a = np.diag([1,2,3,4],k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


**3.Create a 8x8 matrix and fill it with a checkerboard pattern**

In [7]:
import numpy as np
x = np.ones((3,3))
print("Checkboard Pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkboard Pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**4. Normalize a 5x5 random matrix**

In [8]:
import numpy as np
a = np.random.random((5,5))
print("Original Matrix:")
print(a)
xmax,xmin = x.max(),x.min()
a = (x-xmin)/(xmax-xmin)
print("Matrix After Normalisation:")
print(a)

Original Matrix:
[[0.28956131 0.73677469 0.84821436 0.59606402 0.94275697]
 [0.13546804 0.22448836 0.95725276 0.33233024 0.50564876]
 [0.11339075 0.89247627 0.29666833 0.90532557 0.61206009]
 [0.75673795 0.63160913 0.72581613 0.23423637 0.68799845]
 [0.07403047 0.76030539 0.48596779 0.8000492  0.29209008]]
Matrix After Normalisation:
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


** 5.  How to find common values between two arrays?**

In [10]:
import numpy as np
arr1 = np.array([10,20,30,40,50])
print("First Array:", arr1)
arr2 = [10,30,60]
print("Second Array:", arr2)
print("Common values between two arrays:")
print(np.intersect1d(arr1,arr2))

First Array: [10 20 30 40 50]
Second Array: [10, 30, 60]
Common values between two arrays:
[10 30]


**6.How to get the dates of yesterday, today and tomorrow?**

In [3]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-27
Today:  2020-07-28
Tomorrow:  2020-07-29


**7. Consider two random array A and B, check if they are equal**

In [5]:
import numpy as np
a = np.random.randint(0,2,4)
print("First Array: ",a)
b = np.random.randint(0,2,4)
print("Second Array: ",b)
array_equality = np.allclose(a,b)
print("Array Equality: ",array_equality)

First Array:  [1 1 1 1]
Second Array:  [1 0 1 1]
Array Equality:  False


**8.Create random vector of size 10 and replace the maximum value by 0**

In [6]:
import numpy as np
a = np.random.random(10)
print("Original Array:", a)
a[a.argmax()] = 0
print("After replacing max value by 0, array is:")
print(a)

Original Array: [0.50243986 0.82164219 0.30907511 0.19596226 0.68432977 0.32394702
 0.11935861 0.58779298 0.57307978 0.7208602 ]
After replacing max value by 0, array is:
[0.50243986 0.         0.30907511 0.19596226 0.68432977 0.32394702
 0.11935861 0.58779298 0.57307978 0.7208602 ]


**9. How to print all the values of an array?**

In [14]:
import numpy as np
import sys
np.set_printoptions(threshold=sys.maxsize)
x = np.ones((4, 4))
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


**10.Subtract the mean of each row of a matrix"**

In [15]:
import numpy as np
print("Original Matrix:")
a = np.random.rand(5,10)
print(a)
res = a - a.mean(axis=1,keepdims =  True)
print("After subtracting the mean of each row of the matrix:")
print(b)

Original Matrix:
[[0.855761   0.25722817 0.38029925 0.62046061 0.88210461 0.02973214
  0.4226166  0.51623801 0.90008834 0.83727476]
 [0.75408786 0.48434643 0.9774515  0.62239244 0.07349158 0.69884408
  0.30022979 0.81369517 0.17600725 0.35260395]
 [0.39252163 0.09189484 0.74833209 0.65794384 0.12908929 0.55573657
  0.89790388 0.18160528 0.4538517  0.81610778]
 [0.32891642 0.67073841 0.50353501 0.01485807 0.09310973 0.94325159
  0.62684816 0.460432   0.8392989  0.31939795]
 [0.4353958  0.82830501 0.82876191 0.20756657 0.31890276 0.43171448
  0.29210379 0.50158154 0.68658088 0.98070194]]
After subtracting the mean of each row of the matrix:
[1 0 1 1]


**11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?**

In [17]:
import numpy as np
a = np.ones(10)
b = np.random.randint(0,len(a),20)
print("Original matrix:")
print(a)
print("Matrix B:")
print(b)
a +=np.bincount(b,minlength=len(a))
print(a)
np.add.at(a,b,1)
print(a)

Original matrix:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Matrix B:
[1 3 0 4 9 0 2 6 5 9 2 4 1 7 4 0 5 9 9 8]
[4. 3. 3. 2. 4. 3. 2. 2. 2. 5.]
[7. 5. 5. 3. 7. 5. 3. 3. 3. 9.]


**12.How to get the diagonal of a dot product?**

In [28]:
import numpy as np
a = np.asarray([[2,4,2,6],
                [3,7,2,8],
                [1,7,2,6],
                [9,2,0,1]])

b = np.asarray([[3,4,2,6],
                [3,7,2,8],
                [1,7,3,6],
                [9,2,0,2]])

c = np.dot(a,b)
ans = np.diag(np.dot(a,b),k=0)
print("Dot product of the matrices:\n")
print (c)
print("\n")
print("Diagonal of the dot product of the matrices:\n")
print(ans)


Dot product of the matrices:

[[ 74  62  18  68]
 [104  91  26 102]
 [ 80  79  22  86]
 [ 42  52  22  72]]


Diagonal of the dot product of the matrices:

[74 91 22 72]


**13.How to find the most frequent value in an array?**

In [31]:
import numpy as np
a = np.random.randint(0,10,20)
print("Original Array:")
print(a)
print("Most frequent value in the array: ")
print(np.bincount(a).argmax())


Original Array:
[3 6 3 3 9 5 1 5 8 3 0 7 4 3 7 9 6 7 5 8]
Most frequent value in the array: 
3


**14.How to get the n largest values of an array**

In [34]:
import numpy as np
a = np.arange(25)
print("Original Array:")
print(a)
np.random.shuffle(a)
n = 1
print(a[np.argsort(a)[-n:]])

Original Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[24]


 **15.How to create a record array from a regular array?**



In [3]:
import numpy as np
arr1 = np.array([("Geeta Sarvankar",65,165),
                 ("Rohidas Koyande",90,171),
                 ("Santosh Rane",72,168)])
print("Original Array:")
print(arr1)
print("\nRecord Array:")
res = np.core.records.fromarrays(arr1.T,names='col1, col2, col3',formats='S80, f8,i8')
print(res)

Original Array:
[['Geeta Sarvankar' '65' '165']
 ['Rohidas Koyande' '90' '171']
 ['Santosh Rane' '72' '168']]

Record Array:
[(b'Geeta Sarvankar', 65., 165) (b'Rohidas Koyande', 90., 171)
 (b'Santosh Rane', 72., 168)]
